#!/usr/bin/env bash

if [[ -z "$1" ]]; then
  read -rp "Search query 🔎 : " query
else
	query="$1"
fi

query="${query// /+}"
# echo "$query"

urlstring="https://www.googleapis.com/youtube/v3/search?part=snippet&q=${query}&type=video&maxResults=20&key=${YT_API_KEY}"

link="https://$( curl -s "${urlstring}" \
	| jq -r '.items[] | "\(.snippet.channelTitle) => \(.snippet.title) youtu.be/\(.id.videoId)"' \
	| fzf --with-nth='1..-2' +m \
	| awk '{print $NF}' \
)"
echo "$link" | xclip -selection clipboard && echo "Copied to clipboard 👍" 

# echo "https://$( curl -s "${urlstring}" \
# 	| jq -r '.items[] | "\(.snippet.channelTitle) => \(.snippet.title) youtu.be/\(.id.videoId)"' \
# 	| fzf --with-nth='1..-2' +m \
# 	| awk '{print $NF}' \
# )"
