#!/bin/bash

count=0
    # shellcheck disable=SC2034
    for w in $(xdotool search --onlyvisible --desktop \
                       "$(xprop -notype -root _NET_CURRENT_DESKTOP | \
                                                        cut -c 24-)" "" 2>/dev/null) ; do
        count=$((count + 1))
    done

    case "${count}" in
        (1)
            cc="[workspace=\"__focused__\" instance=\"Alacritty\"]"
            cmds="floating enable;"
            i3-msg "$(printf "%s %s" "${cc}" "${cmds}")"
            ;;
        (2)
            cc="[workspace=\"__focused__\" instance=\"Alacritty\"]"
            cmds="floating disable;"
            i3-msg "$(printf "%s %s" "${cc}" "${cmds}")"
            ;;
    esac
