#!/usr/bin/env bash

# Script name: dm-colpick
# Description: Copy a color to your clipboard using dmenu, change the colors if needed
# Dependencies: dmenu, xclip

set -euo pipefail

_path="$(cd "$(dirname "$BASH_SOURCE")" && cd "$(dirname "$(readlink "$BASH_SOURCE" || echo ".")")" && pwd)"
if [[  -f ${_path}/_dm-helper ]]; then
  # shellcheck disable=SC1090,SC1091
  source "${_path}/_dm-helper"
else
  # shellcheck disable=SC1090
  echo "No helper-script found"
fi

# script will not hit this if there is no config-file to load
# shellcheck disable=SC1090
source "$(get_config)"


main() {
  # As this is loaded from other file it is technically not defined
  # shellcheck disable=SC2154
  selected="$(printf '%s\n' "${!colpick_list[@]}" | $DMENU "color:" "$@")"
  [[ -z "$selected" ]] && exit 1
  echo "${colpick_list["$selected"]}" | cp2cb
}

[[ "$BASH_SOURCE" = "$0" ]] && main "$@"
