#!/usr/bin/env bash

# Script name: dm-dictionary
# Description: uses the translate package as a dictionary
# Dependencies: translate-shell, didyoumean

set -euo pipefail

set -x
_path="$(cd "$(dirname "$BASH_SOURCE")" && cd "$(dirname "$(readlink "$BASH_SOURCE" || echo ".")")" && pwd)"
if [[  -f "${_path}/_dm-helper" ]]; then
  # shellcheck disable=SC1090,SC1091
  source "${_path}/_dm-helper"
else
  # shellcheck disable=SC1090
  echo "No helper-script found"
fi

# script will not hit this if there is no config-file to load
# shellcheck disable=SC1090
source "$(get_config)"

main() {
  # : means true
	WORD="$(: | $DMENU "Search:")"
	TESTWORD="$(dym -c -n 1 "$WORD")"

	if [[ "$WORD" != "$TESTWORD" ]]; then
		KEYWORD=$(dym -c "$WORD" | $DMENU "was $WORD a misspelling?(select/no)")
		if [[ "$KEYWORD" = "no" || "$KEYWORD" = "n" ]]; then
			KEYWORD="$WORD"
		fi
	else
		KEYWORD="$WORD"
	fi

	if ! [[ $KEYWORD ]]; then
		printf 'No word inserted\n' >&2
		exit 0
	fi
	$DMTERM trans -v -d "$WORD"
}

[[ "$BASH_SOURCE" = "$0" ]] && main "$@"
