#!/bin/bash
#
# Script name: dm-documents
# Description: Search for a process to kill.
# Dependencies: dmenu

set -euo pipefail
_path="$(cd "$(dirname "$BASH_SOURCE")" && cd "$(dirname "$(readlink "$BASH_SOURCE" || echo ".")")" && pwd)"
if [[  -f "${_path}/_dm-helper" ]]; then
  # shellcheck disable=SC1090,SC1091
  source "${_path}/_dm-helper"
else
  # shellcheck disable=SC1090
  echo "No helper-script found"
fi

# script will not hit this if there is no config-file to load
# shellcheck disable=SC1090
source "$(get_config)"

main(){
  # PDF_VIEWER=zathura
  files="$(find "$HOME" -maxdepth 4 -iname "*.pdf")"
  choice=$( printf '%s\n' "${files[@]}" | \
        cut -d '/' -f4- | \
        sed -e 's/Documents/Dcs/g' \
        -e 's/Downloads/Dwn/g' \
        -e 's/Pictures/Pic/g' \
        -e 's/Images/Img/g' \
        -e 's/.pdf//g' | \
        sort -g | \
      $DMENU "File: " "$@") || exit 1
  if [ "$choice" ]; then
      file=$( printf '%s' "$choice" | \
        sed -e 's/Dcs/Documents/g' \
        -e 's/Dwn/Downloads/g' \
        -e 's/Pic/Pictures/g' \
        -e 's/Img/Images/g' \
  )
        "$PDF_VIEWER" "$HOME/${file}.pdf"
  else
    echo "Program Terminated." && exit 0
  fi
}

[[ "$BASH_SOURCE" = "$0" ]] && main "$@"
