#!/usr/bin/env bash

# Script name: dm-maim
# Description: Choose type of screenshot to take with maim.
# Dependencies: dmenu, maim, tee, xdotool, xclip

set -euo pipefail

_path="$(cd "$(dirname "$BASH_SOURCE")" && cd "$(dirname "$(readlink "$BASH_SOURCE" || echo ".")")" && pwd)"
if [[  -f "${_path}/_dm-helper" ]]; then
  source "${_path}/_dm-helper"
else
  echo "No helper-script found"
fi

source "$(get_config)"

get_timestamp() {
  date '+%Y%m%d-%H%M%S'
}

notify() {
  notify-send "Saved screenshot" "${1/#$HOME/\~}"
}

tmux_bar() {
    checkBin tmux && tmux set status on
}
checkBin tmux && tmux set status off

main() {

  local _maim_args=""
  local _file_type=""

  # Makes sure the directory exists.
  # shellcheck disable=SC2154
  mkdir -p "$maim_dir"

  declare -a modes=(
  "Fullscreen"
  "Active window"
  "Selected region"
  )

  target=$(printf '%s\n' "${modes[@]}" | $DMENU 'Take screenshot of:' "$@") || exit 1
  case "$target" in
    'Fullscreen')
      _file_type="full"
    ;;
    'Active window')
      active_window=$(xdotool getactivewindow)
      _maim_args="-i $active_window"
      _file_type="window"
    ;;
    'Selected region')
      _maim_args="-s"
      _file_type="region"
    ;;
  esac

  delay=$(printf '%s\n' "$(seq 0 5)" | $DMENU 'Delay (in seconds):' "$@" ) || exit 1
  if [ ! "$delay" -eq "0" ]; then
    _maim_args="${_maim_args} --delay=$delay"
  else
    _maim_args="${_maim_args} --delay=0.5"
  fi

  _maim_args="${maim_args} ${_maim_args}"
  local file="${maim_dir}/${maim_file_prefix}-${_file_type}-$(get_timestamp).png"
  maim ${_maim_args} | tee "$file" | cp2cb-maim
  echo "screenshot $file" >> "$lastactionfile"
  notify "$file"

  # local destination=( "File" "Clipboard" "Both" )
  # dest=$(printf '%s\n' "${destination[@]}" | $DMENU 'Destination:' "$@" ) || exit 1
  # case "$dest" in
  #   'File')
  #     # shellcheck disable=SC2086,SC2154
  #     maim ${_maim_args} "$file"
  #     echo "screenshot $file" >> "$lastactionfile"
  #     notify "$file"
  #   ;;
  #   'Clipboard')
  #     shellcheck disable=SC2086
  #     maim ${_maim_args} | cp2cb-maim
  #     notify-send "Saved screenshot" "Clipboard"
  #   ;;
  #   'Both')
  #     # shellcheck disable=SC2086
  #     maim ${_maim_args} | tee "$file" | cp2cb-maim
  #     echo "screenshot $file" >> "$lastactionfile"
  #     notify "$file"
  #   ;;
  #   *)
  #     exit 1
  #   ;;
  # esac
}

trap tmux_bar EXIT
[[ "$BASH_SOURCE" = "$0" ]] && main "$@"
