#!/usr/bin/env bash

# Script name: dm-maim
# Description: Choose type of screenshot to take with maim.
# Dependencies: dmenu, maim, tee, xdotool, xclip

set -euo pipefail

_path="$(cd "$(dirname "$BASH_SOURCE")" && cd "$(dirname "$(readlink "$BASH_SOURCE" || echo ".")")" && pwd)"
if [[  -f "${_path}/_dm-helper" ]]; then
  # shellcheck disable=SC1090,SC1091
  source "${_path}/_dm-helper"
else
  # shellcheck disable=SC1090
  echo "No helper-script found"
fi

# script will not hit this if there is no config-file to load
# shellcheck disable=SC1090
source "$(get_config)"
# Defining our config location

get_timestamp() {
  date '+%d-%m-%Y_%H-%M-%S'
}

cp2cb-maim() {
  case "$XDG_SESSION_TYPE" in
    'x11') xclip -selection clipboard -t image/png;;
    'wayland') wl-copy -t image/png;;
    *) err "Unknown display server";;
  esac
}

main() {
  local _maim_args=""
  local _file_type=""
  # Makes sure the directory exists.
  # shellcheck disable=SC2154
  mkdir -p "${maim_dir}"

  declare -a modes=(
  "Fullscreen"
  "Active window"
  "Selected region"
  )

  target=$(printf '%s\n' "${modes[@]}" | $DMENU 'Take screenshot of:' "$@") || exit 1
  case "$target" in
    'Fullscreen')
      _file_type="full"
    ;;
    'Active window')
      active_window=$(xdotool getactivewindow)
      _maim_args="-i $active_window"
      _file_type="window"
    ;;
    'Selected region')
      _maim_args="-s"
      _file_type="region"
    ;;
  esac

  delay=$(printf '%s\n' "$(seq 0 5)" | $DMENU 'Delay (in seconds):' "$@" ) || exit 1
  if [ ! "$delay" -eq "0" ]; then
    _maim_args="${_maim_args} --delay=$delay"
  else
    _maim_args="${_maim_args} --delay=0.5"
  fi

  _maim_args="${_maim_args} -q -u -B -m 1"
  local destination=( "File" "Clipboard" "Both" )
  dest=$(printf '%s\n' "${destination[@]}" | $DMENU 'Destination:' "$@" ) || exit 1
  case "$dest" in
    'File')
      # shellcheck disable=SC2086,SC2154
      maim ${_maim_args} "${maim_dir}/${maim_file_prefix}-${_file_type}-$(get_timestamp).png"
      notify-send "Saved screenshot" "${maim_dir}/${maim_file_prefix}-${_file_type}-$(get_timestamp).png"
    ;;
    'Clipboard')
      # shellcheck disable=SC2086
      maim ${_maim_args} | cp2cb-maim
      notify-send "Saved screenshot" "Clipboard"
    ;;
    'Both')
      # shellcheck disable=SC2086
      maim ${_maim_args} | tee "${maim_dir}/${maim_file_prefix}-${_file_type}-$(get_timestamp).png" | cp2cb-maim
      notify-send "Saved screenshot" "${maim_dir}/${maim_file_prefix}-${_file_type}-$(get_timestamp).png and clipboard"
    ;;
    *)
      exit 1
    ;;
  esac

}

[[ "$BASH_SOURCE" = "$0" ]] && main "$@"
