#!/usr/bin/env bash
#
# Script name: dm-dictionary
# Description: uses the translate package as a dictionary
# Dependencies: didyoumean

set -euo pipefail

_path="$(cd "$(dirname "$BASH_SOURCE")" && cd "$(dirname "$(readlink "$BASH_SOURCE}" || echo ".")")" && pwd)"
if [[  -f "${_path}/_dm-helper" ]]; then
  # shellcheck disable=SC1090,SC1091
  source "${_path}/_dm-helper"
else
  # shellcheck disable=SC1090
  echo "No helper-script found"
fi

# script will not hit this if there is no config-file to load
# shellcheck disable=SC1090
source "$(get_config)"

main() {
WORD="$(: | $DMENU "Enter Word:")"

if ! [ "$WORD" ] || [ "$WORD" = "quit" ]; then
	printf 'No word inserted\n' >&2
	exit 0
fi

dym -c "$WORD" | $DMENU "Select Correct Spelling:" | xclip -selection clipboard
}

[[ "$BASH_SOURCE" = "$0" ]] && main "$@"
