#!/usr/bin/env bash

# Script name: dm-websearch
# Description: Search various search engines (inspired by surfraw).
# Dependencies: dmenu and brave

set -euo pipefail

_path="$(cd "$(dirname "$BASH_SOURCE")" && cd "$(dirname "$(readlink "$BASH_SOURCE" || echo ".")")" && pwd)"
if [[  -f "${_path}/_dm-helper" ]]; then
  # shellcheck disable=SC1090,SC1091
  source "${_path}/_dm-helper"
else
  # shellcheck disable=SC1090
  echo "No helper-script found"
fi

# script will not hit this if there is no config-file to load
# shellcheck disable=SC1090
source "$(get_config)"

main() {
  # As this is loaded from other file it is technically not defined
  # shellcheck disable=SC2154 # Choosing  a search engine by name from array above.
  engine=$(printf '%s\n' "${!websearch[@]}" | sort | $DMENU 'Choose search engine:' "$@") || exit 1

  # Getting the URL of the search engine we chose.
  url="${websearch["$engine"]}"

  # Searching the chosen engine.
  query=$(echo "$engine" | $DMENU 'Enter search query:')

  query="$(echo -n "$query" | jq -s -R -r @uri)"
  # Display search results in web browser
  # shellcheck disable=SC2154
  $DMBROWSER "${url}${query}"
}

[[ "$BASH_SOURCE" = "$0" ]] && main "$@"
