#!/usr/bin/env bash

# Script name: dm-weather
# Description: Simple graphical weather app
# Dependencies: dmenu, curl, yad

set -eo pipefail

_path="$(cd "$(dirname "$BASH_SOURCE")" && cd "$(dirname "$(readlink "$BASH_SOURCE" || echo ".")")" && pwd)"
if [[  -f "${_path}/_dm-helper" ]]; then
  # shellcheck disable=SC1090,SC1091
  source "${_path}/_dm-helper"
else
  # shellcheck disable=SC1090
  echo "No helper-script found"
fi

# script will not hit this if there is no config-file to load
# shellcheck disable=SC1090
source "$(get_config)"

main() {
  # Here we obtain the location from the list in the config
  # As this is loaded from other file it is technically not defined
  # shellcheck disable=SC2154
  _location="$(printf '%s\n' "${!weather_location[@]}" | $DMENU "Where do you want to see the weather?")"

  # If $weather_opts is unset, give it an empty value
  weather_opts+=''

  # Curl wttr.in, a CLI weather app.
  # TODO: Replace YAD with some simplified notification
  curl -s "https://wttr.in/\"${weather_location[$_location]}\"?T&${weather_opts}" | yad --text-info
}

[[ "$BASH_SOURCE" = "$0" ]] && main "$@"
